# NUMPY

In [1]:
#NUMPY
#Numpy is a library in python that helps you to do scientific computing. 
#it is used to create arrays of object.
#It is also used to generate random numbers
#First thing to do is to import your library

In [2]:
import numpy as np

In [4]:
#create an array
lst = [1,2,3,4]
arr = np.array([lst])
print(arr)
print(type(arr))

[[1 2 3 4]]
<class 'numpy.ndarray'>


In [5]:
#You can also create a NumPy array by just passing the list directly into the np.array method
arr = np.array([4,5,6,7])
arr

array([4, 5, 6, 7])

In [6]:
#Two Dimentional (2D) array
b = np.array([(1,2,3), (4,5,6)])
print(b)
print ('...........')
print(b.dtype)

[[1 2 3]
 [4 5 6]]
...........
int32


In [22]:
#creating an array and specifying the data type to be a float
data = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]], float)
print(data)
print('-------------------------')
print(f'The data type of the array is:', data.dtype)

[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]]
-------------------------
The data type of the array is: float64


In [23]:
#The size of an array is the number of elemnt in it. The shape is configuration of its rows 
#and columns
print(data.size)
print(data.shape)

12
(3, 4)


In [8]:
#Using the ‘in’ statement in np array. This operation returns a boolean
7 in data

True

In [9]:
25 in data

False

In [10]:
#You can create an array with a range of elements
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.array(range(10))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
#You can also create an array that contains a range of evenly spaced intervals.
np.arange(4,22,4)

array([ 4,  8, 12, 16, 20])

In [13]:
#You can also use np.linspace() to create an array with values that are spaced linearly in a 
#specified interval
np.linspace(1,4,10)

array([1.        , 1.33333333, 1.66666667, 2.        , 2.33333333,
       2.66666667, 3.        , 3.33333333, 3.66666667, 4.        ])

In [14]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [15]:
np.zeros((2,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [28]:
#identity Matrix
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [29]:
#using the fill method 
d = np.array([[2,3,4,5],[5,6,7,8]])
print(d)
print('................')
d.fill(9)
print(d)

[[2 3 4 5]
 [5 6 7 8]]
................
[[9 9 9 9]
 [9 9 9 9]]


In [47]:
#Generating random numbers between 0 and 1 following the shape (3 rows and 4 columns) passed in.
np.random.rand(3, 4)

array([[0.50848503, 0.80029377, 0.29722934, 0.81824661],
       [0.21799755, 0.49310146, 0.10912868, 0.21845793],
       [0.55861356, 0.43576104, 0.34297644, 0.3768381 ]])

In [48]:
#This will give a random integer value within the range specified
np.random.randint(4,9)

5

Slicing in numpy array

In [18]:
data = np.arange(20)
data

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [19]:

"""By simply specifying where you want to slice your array, 
you can easily create a new array from a section of your array (already created)"""

new_data = data[5:12]
new_data

array([ 5,  6,  7,  8,  9, 10, 11])

In [20]:
"""With negative indexing, you can select from the back. -1 refers to the last element of the array, 
-2 is the second to the last element of the array"""

new_data2 = data[-6:-2]
new_data2

array([14, 15, 16, 17])

In [24]:
#Already created an array called data in previous cell.
data

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.]])

In [25]:
data[:2,:3]

array([[1., 2., 3.],
       [5., 6., 7.]])

In [26]:
data[-3:-1,:-1]

array([[1., 2., 3.],
       [5., 6., 7.]])

In [27]:
#changing the value of an array element
data[1,2]=700
data

array([[  1.,   2.,   3.,   4.],
       [  5.,   6., 700.,   8.],
       [  9.,  10.,  11.,  12.]])

In [30]:
#Stacking is a way of merging/combining your arrays together
#Horizontal stacking
g = np.array([(0,1,2,3), (4,5,6,7)])
f = np.array([(10,11,12,13),(15,16,17,18)])
print(f)
print('................')
print(g)
print('................')
print(np.hstack((f,g)))

[[10 11 12 13]
 [15 16 17 18]]
................
[[0 1 2 3]
 [4 5 6 7]]
................
[[10 11 12 13  0  1  2  3]
 [15 16 17 18  4  5  6  7]]


In [31]:
#Vertical stacking
g = np.array([(0,1,2,3), (4,5,6,7)])
f = np.array([(10,11,12,13),(15,16,17,18)])
print(f)
print('................')
print(g)
print('................')
print(np.vstack((f,g)))

[[10 11 12 13]
 [15 16 17 18]]
................
[[0 1 2 3]
 [4 5 6 7]]
................
[[10 11 12 13]
 [15 16 17 18]
 [ 0  1  2  3]
 [ 4  5  6  7]]


BASIC OPERATIONS IN ARRAY

In [ ]:
#Once you have created your arrays, you can perform operations such as addition, 
#subtraction, division, multiplication and more

In [32]:
#Addition of arrays
g = np.array([(0,1,2,3), (4,5,6,7)])
f = np.array([(10,11,12,13),(15,16,17,18)])
print(g)
print('................')
print(f)
print('................')
print(f'Result of adding the arrays below')
f + g

[[0 1 2 3]
 [4 5 6 7]]
................
[[10 11 12 13]
 [15 16 17 18]]
................
Result of adding the arrays below


array([[10, 12, 14, 16],
       [19, 21, 23, 25]])

In [33]:
print(f'Result of subtracting the arrays below')
print(f -g)
print(f'Result of dividing the arrays below')
print(f / g)
print(f'Result of multiplying the arrays below')
print(f * g)

Result of subtracting the arrays below
[[10 10 10 10]
 [11 11 11 11]]
Result of dividing the arrays below
[[        inf 11.          6.          4.33333333]
 [ 3.75        3.2         2.83333333  2.57142857]]
Result of multiplying the arrays below
[[  0  11  24  39]
 [ 60  80 102 126]]


C:\Users\stephen\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: RuntimeWarning: divide by zero encountered in true_divide
  after removing the cwd from sys.path.


In [34]:
#Axis in array
#Rows are called axis 1, columns are 0
f = np.array([(1,2,3,4),(5,6,7,8)])
print(f)
print('.................')
print(f.sum(axis=0))

[[1 2 3 4]
 [5 6 7 8]]
.................
[ 6  8 10 12]


In [35]:
print(f.sum(axis=1))
print('.................')
print(np.sqrt(f))
print('.................')
print(np.std(f))

[10 26]
.................
[[1.         1.41421356 1.73205081 2.        ]
 [2.23606798 2.44948974 2.64575131 2.82842712]]
.................
2.29128784747792


In [46]:
#You can find the mean, minimum value, maximum value using the functions below
#f.min()
#f.mean()
f.sum()

36

Floor, Ceil, and Rint

In [36]:
"""The floor is used to round a number down. It gives the lower interger while the Ceil gives the
uper integer and the Rint rounds to the nearest integer."""
act = np.array([4.544, 7.238, 3.68])
act

array([4.544, 7.238, 3.68 ])

In [37]:
np.floor(act)

array([4., 7., 3.])

In [38]:
np.ceil(act)

array([5., 8., 4.])

In [39]:
np.rint(act)

array([5., 7., 4.])

Reshape and Transpose your Array

In [ ]:
"""It’s common to need to switch the dimensions of a matrix. This can happen when, for example, you have a model 
that expects a certain input shape that is different from your dataset. 
This is where the reshape method comes to play. You simply pass in the new dimensions that 
you want for the matrix."""

In [40]:
print(f)
print('...........................')
print(f.reshape(4,2))

[[1 2 3 4]
 [5 6 7 8]]
...........................
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [ ]:
"""NumPy arrays have the property T that allows you to transpose a matrix. 
The transpose() method gives the same result as using T."""

In [41]:
print(f)
print('...........................')
print(f.transpose())

[[1 2 3 4]
 [5 6 7 8]]
...........................
[[1 5]
 [2 6]
 [3 7]
 [4 8]]


In [43]:
f

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [44]:
#ravel helps to arrange our arrays (2D and higher dimesions in a staright line)
f.ravel()
#the 'flatten' function works exactly as ravel.

array([1, 2, 3, 4, 5, 6, 7, 8])

Load and Save your Array

In [ ]:
#You will, at some point, want to save your arrays to disk and load them back without having 
#to re-run the code

In [49]:
k = np.arange(14)
#You can save it as “filename.npy”. I have specified 'my_array' to be the name am saving it as.
np.save('my_array', k)

In [50]:
#To load the saved array
arr = np.load('my_array.npy')
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])